use [Tech shop DB]
--------------------------------------TASK 3--------------------------------------------------------------------------------
-- 1. Retrieve orders with customer information
SELECT 
    Orders.OrderID,
    Customers.CustomerID
FROM 
    Orders
JOIN 
    Customers ON Orders.CustomerID = Customers.CustomerID;

-- 2. Find the total revenue generated by each electronic gadget product
 SELECT p.ProductName, SUM(od.Quantity * p.Price) AS TotalRevenue
 FROM OrderDetails od
 JOIN Products p ON od.ProductID = p.ProductID
 GROUP BY p.ProductName;
 
 -- 3. List all customers who have made at least one purchase
 SELECT DISTINCT c.First_Name, c.Last_Name, c.Email, c.Phone
 FROM Customers c
 JOIN Orders o ON c.CustomerID = o.CustomerID;
 
 -- 4. Find the most popular electronic gadget (highest total quantity ordered)
 SELECT TOP 1 p.ProductName, SUM(od.Quantity) AS TotalQuantityOrdered
 FROM OrderDetails od
 JOIN Products p ON od.ProductID = p.ProductID
 GROUP BY p.ProductName
 ORDER BY TotalQuantityOrdered DESC;
 
 -- 5. Retrieve a list of electronic gadgets along with their descriptions
 SELECT p.ProductName, p.Description
 FROM Products p;
 
 -- 6. Calculate the average order value for each customer
 SELECT c.First_Name, c.Last_Name, AVG(o.TotalAmount) AS AverageOrderValue
 FROM Customers c
 JOIN Orders o ON c.CustomerID = o.CustomerID
 GROUP BY c.CustomerID, c.First_Name, c.Last_Name;
 
 -- 7. Find the order with the highest total revenue
 SELECT TOP 1 o.OrderID, c.First_Name, c.Last_Name, c.Email, c.Phone, o.TotalAmount
 FROM Orders o
 JOIN Customers c ON o.CustomerID = c.CustomerID
 ORDER BY o.TotalAmount DESC;
 
 -- 8. List electronic gadgets and the number of times each product has been ordered
 SELECT p.ProductName, COUNT(od.ProductID) AS NumberOfTimesOrdered
 FROM OrderDetails od
 JOIN Products p ON od.ProductID = p.ProductID
 GROUP BY p.ProductName;
 
 -- 9. Find customers who have purchased a specific electronic gadget
 -- Replace 'Laptop' with the actual product name when querying
 SELECT DISTINCT c.First_Name, c.Last_Name, c.Email, c.Phone
 FROM Customers c
 JOIN Orders o ON c.CustomerID = o.CustomerID
 JOIN OrderDetails od ON o.OrderID = od.OrderID
 JOIN Products p ON od.ProductID = p.ProductID
 WHERE p.ProductName = 'Laptop';
 
 -- 10. Calculate the total revenue generated by all orders within a specific time period
 -- Replace '2025-03-10' and '2025-03-20' with actual date range when querying
 SELECT SUM(o.TotalAmount) AS TotalRevenue
 FROM Orders o
 WHERE o.OrderDate BETWEEN '2025-03-10' AND '2025-03-20';


 --TASK 4

 --1. Find out which customers have not placed any orders
 SELECT c.First_Name, c.Last_Name
 FROM Customers c
 LEFT JOIN Orders o ON c.CustomerID = o.CustomerID
 WHERE o.CustomerID IS NULL;
 
 -- 2. Find the total number of products available for sale
 SELECT COALESCE(SUM(i.QuantityInStock), 0) AS TotalProductsAvailable
 FROM Inventory i
 LEFT JOIN Products p ON i.ProductID = p.ProductID;
 
 
 -- 3. Calculate the total revenue generated by TechShop
 SELECT SUM(o.TotalAmount) AS TotalRevenue
 FROM Orders o;
 
 -- 4. Calculate the average quantity ordered for a specific product
 -- Replace 'Laptop' with an actual product name when querying
 SELECT AVG(od.Quantity) AS AvgQuantityOrdered
 FROM OrderDetails od
 JOIN Products p ON od.ProductID = p.ProductID
 WHERE p.ProductName = 'Laptop';
 
 -- 5. Calculate the total revenue generated by a specific customer
 -- Replace 5 with an actual CustomerID when querying
 SELECT SUM(o.TotalAmount) AS TotalRevenue
 FROM Orders o
 WHERE o.CustomerID = 5;
 
 -- 6. Find the customer who has placed the most orders
 SELECT TOP 1 c.First_Name, c.Last_Name, COUNT(o.OrderID) AS NumOrders
 FROM Customers c
 JOIN Orders o ON c.CustomerID = o.CustomerID
 GROUP BY c.CustomerID, c.First_Name, c.Last_Name
 ORDER BY NumOrders DESC;
 
 -- 7. Find the most popular product based on total quantity ordered
 SELECT TOP 1 p.ProductName, SUM(od.Quantity) AS TotalQuantityOrdered
 FROM OrderDetails od
 JOIN Products p ON od.ProductID = p.ProductID
 GROUP BY p.ProductName
 ORDER BY TotalQuantityOrdered DESC;
 
 -- 8. Find the customer who has spent the most money on products
 SELECT TOP 1 c.First_Name, c.Last_Name, SUM(o.TotalAmount) AS TotalSpending
 FROM Orders o
 JOIN Customers c ON o.CustomerID = c.CustomerID
 GROUP BY c.CustomerID, c.First_Name, c.Last_Name
 ORDER BY TotalSpending DESC;
 
 -- 9. Calculate the average order value for all customers
 SELECT c.First_Name, c.Last_Name, AVG(o.TotalAmount) AS AvgOrderValue
 FROM Customers c
 JOIN Orders o ON c.CustomerID = o.CustomerID
 GROUP BY c.CustomerID, c.First_Name, c.Last_Name;
 
 -- 10. Find the total number of orders placed by each customer
 SELECT c.First_Name, c.Last_Name, COUNT(o.OrderID) AS NumOrders
 FROM Customers c
 JOIN Orders o ON c.CustomerID = o.CustomerID
 GROUP BY c.CustomerID, c.First_Name, c.Last_Name;


